baseURL = "https://kishore96in.github.io/"
languageCode = "en-in"
title = "Kishore's homepage"
pluralizelisttitles = false

[caches]
	#For caching in GitHub Actions builds
	[caches.images]
		dir = ':cacheDir/images'

#For math rendering
[markup.goldmark.extensions.passthrough]
	enable = true
[markup.goldmark.extensions.passthrough.delimiters]
	block = [['\[', '\]'], ['$$', '$$']]
	inline = [['\(', '\)'], ['$', '$']]
